language: node_js
node_js:
  - "7"
install:
  - npm install -g kyt-cli
  - kyt-cli setup -p npm -d kyt -r https://github.com/cleverfranke/cf-kyt-starter-universal-redux.git
script:
  - npm run lint
  - npm run test
notifications:
  email: false
