language: node_js
node_js:
  - "6"
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - npm install -g kyt-cli yarn
  - kyt-cli setup -p yarn -d kyt --local-path ./cf-kyt-starter-universal-redux/
  - cd kyt
script:
  - npm run lint
  - npm run test
notifications:
  email: false
