version: '3'

services:

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    links:
      - web-production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./cache:/tmp/cache

  web-production:
    build:
      context: ./
      dockerfile: Dockerfile-production
    volumes:
      - .:/code/
      - front-end-deps-production:/code/node_modules
      - dist-production:/code/build

volumes:
    front-end-deps-production:
    dist-production:
