version: '2'

services:

  nginx:
    image: nginx:1.11.10
    ports:
      - 80:80
      - 443:443
    restart: always
    links:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./cache:/tmp/cache

  web:
    build: .
    command: npm run start
    ports:
      - '8000:8000'
    volumes:
      - .:/code/
      - /code/node_modules
