version: '3'

services:

  web-production:
    build:
      context: ./
      dockerfile: Dockerfile-production
    ports:
      - '8000:8000'
    volumes:
      - .:/code/
      - front-end-deps-production:/code/node_modules
      - dist-production:/code/build

volumes:
    front-end-deps-production:
    dist-production:
